spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password:
  
  h2:
    console:
      enabled: true
      path: /h2-console

  session:
    store-type: jdbc

mybatis:
  configuration:
    underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  type-handlers-package: jp.co.teruuu.ec_modeling.infla.data.typehandler

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    corsEnabled: true

graphiql:
  enabled: true
  mapping: /graphiql
  endpoint:
    graphql: /graphql

